$(function() {

  $('button.call').on('click', function(e) {
    Swal.mixin({
      input: 'text',
      confirmButtonText: 'Next &rarr;',
      showCancelButton: true,
      progressSteps: ['1', '2']
    }).queue([
      {
        title: "Phone #1",
        text: 'Please enter your phone to initiate Twilio call'
      },
      {
        title: "Phone #2",
        text: 'Please enter real phone instead of autogenerated'
      }
    ]).then((result) => {
      if (result.value) {
        $.ajax({
          url: 'site/call',
          method: 'POST',
          dataType: 'json',
          data: {
            adminPhone: result.value[0],
            providerPhone: result.value[1]
          }
        }).done(function(data) {
          Swal.fire({
            icon: 'info',
            title: 'Done',
            text: data.message,
          });
        }).fail(function(error) {
          Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: error.responseText, // JSON.stringify(error),
          });
        });
        const answers = JSON.stringify(result.value)
        Swal.fire('Connecting...');
      }
    });
  });

  $('button.custom-call').on('click', function(e) {
    Swal.mixin({
      input: 'text',
      confirmButtonText: 'Next &rarr;',
      showCancelButton: true,
      progressSteps: ['1', '2', '3', '4', '5']
    }).queue([
      {
        title: "Account SID",
        text: 'Please enter Twilio account SID'
      },
      {
        title: "Auth tocken",
        text: 'We need also Twilio auth token'
      },
      {
        title: "Twilio number",
        text: 'To make calls possible you should enter Twilio number'
      },
      {
        title: "Phone #1",
        text: "Please enter Admin's number"
      },
      {
        title: "Phone #2",
        text: "Please enter user's number"
      }
    ]).then((result) => {
      if (result.value) {
        $.ajax({
          url: 'site/call',
          method: 'POST',
          dataType: 'json',
          data: {
            accountSid: result.value[0],
            authToken: result.value[1],
            twilioNumber: result.value[2],
            adminPhone: result.value[3],
            providerPhone: result.value[4]
          }
        }).done(function(data) {
          Swal.fire({
            icon: 'info',
            title: 'Done',
            text: data.message,
          });
        }).fail(function(error) {
          Swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: error.responseText, // JSON.stringify(error),
          });
        });
        Swal.fire('Connecting...');
      }
    });
  });
});